defaults:
    - IndustRealBase
    - _self_

name: 'grasp_handle'
use_init_states: True     
headless: True            # open viewer with render=True instead
physics_engine: "physx"

env:
  numEnvs: ${resolve_default:8192,${...num_envs}}
  numObservations: 73
  numActions: 6
  episode_length: 120
  
  val_ratio: ${resolve_default:0.0,${...val_ratio}}

  # camera properties
  camera:
    width: 1440
    height: 960

  object_friction: 1.0

  # partnet
  object_code: ${...object_code}
  object_list: ${...object_list}

sampler:
  # inverse kinematics coefficient
  damping: 0.10

  # threshold for accepting IK results
  ik_solver_pos_tolerance: 0.05
  ik_solver_rot_tolerance: 0.04

  # max number of IK iterations
  max_ik_iters: 15

  # max number of backtrack iterations
  max_backtrack_iters: 20

  # noise for sampling eef position: 
  # eef position is sampled from a half-sphere with radius target_eef_radius centered at target object position
  # for vision-based sampling, the radius is set to half of this value
  target_eef_radius: 0.08

rl:
  # episode length
  max_episode_length: ${..env.episode_length}

  # actions
  pos_action_scale: [0.05, 0.05, 0.05]
  rot_action_scale: [0.05, 0.05, 0.05]
  force_action_scale: [1.0, 1.0, 1.0]
  torque_action_scale: [1.0, 1.0, 1.0]

  clamp_rot: True
  clamp_rot_thresh: 1.0e-6

  # reward settings
  dist_object_gripper_reward_temp: -1.0
  dist_object_dof_pos_reward_temp: -100.0
  gripper_direction_reward_temp: 0.5
  gripper_direction_threshold: 0.8
  eef_height_consistency_reward_temp: -40.0
  success_bonus: 15.0
  success_threshold: 0.005

  num_object_keypoints: 16
  gripper_keypoint_dof: 5
  gripper_keypoint_scale: 0.5

  enable_object_in_view_reward: False
  object_in_view_reward_temp: -0.8
  object_in_view_reward_threshold: 0.27

randomize:
  franka_arm_initial_dof_pos: [0, -0.5, 0, -3.0, 0, 3, 0.7854]
  franka_gripper_initial_state: 1.0

  object_pos_radius: 0.7
  object_pos_radius_noise: 0.05
  door_pos_radius_offset: 0.15
  object_pos_angle_noise: 1.57079   # pi / 2
  object_z_max: 0.80
  handle_z_min: 0.15
  door_rotation_noise: 0.26180      # pi / 12
  drawer_rotation_noise: 0.78540    # pi / 4

  object_dof_damping_lower: 1.0
  object_dof_damping_upper: 2.0
  object_dof_friction_lower: 0.25
  object_dof_friction_upper: 0.50
  door_damping_scale: 0.10
  door_friction_scale: 0.10

  max_object_init_dof_ratio: 0.9

ctrl:
  all:
    gripper_prop_gains: [200, 200]      # 500 -> 100 alleviate penetration
    gripper_deriv_gains: [1, 1]
  task_space_impedance:
    motion_ctrl_axes: [1, 1, 1, 1, 1, 1]
    task_prop_gains: [300, 300, 300, 50, 50, 50]
    task_deriv_gains: [34, 34, 34, 1.4, 1.4, 1.4]
