defaults:
    - IndustRealBase
    - _self_

name: 'open'
use_init_states: True     
headless: True            # open viewer with render=True instead
physics_engine: "physx"

env:
  numEnvs: ${resolve_default:8192,${...num_envs}}
  numObservations: 78
  numActions: 6
  episode_length: 120
  
  val_ratio: ${resolve_default:0.0,${...val_ratio}}

  # camera properties
  camera:
    width: 1440
    height: 960

  object_friction: 1.0

  # partnet
  object_code: ${...object_code}
  object_list: ${...object_list}

sampler:
  # number of RL steps for grasp policy
  num_rl_steps: 120
  # number of steps for closing gripper
  num_close_gripper_steps: 60
  # number of steps for randomizing franka and object pose
  num_randomization_steps: 20

  # for each grasp result, we sample multiple randomized states
  num_randomization_per_policy: 5

  # configuration for grasp handle policy
  # resolve the value of policy_init_states_path and policy_checkpoint_path programmatically
  # too complicated to be resolved in the config file
  policy_init_states_path: ""
  policy_config_path: "config/train/grasp_handle.yaml"
  policy_checkpoint_path: ""

rl:
  # episode length
  max_episode_length: ${..env.episode_length}

  # actions
  pos_action_scale: [0.05, 0.05, 0.05]
  rot_action_scale: [0.05, 0.05, 0.05]
  force_action_scale: [1.0, 1.0, 1.0]
  torque_action_scale: [1.0, 1.0, 1.0]

  clamp_rot: True
  clamp_rot_thresh: 1.0e-6

  # reward settings
  dist_object_gripper_reward_temp: 0.0
  dist_object_dof_pos_reward_temp: -2.5
  grasp_pos_offset_reward_temp: -30.0
  gripper_direction_reward_temp: 0.5
  gripper_direction_threshold: 0.8
  action_penalty_temp: -0.4
  action_penalty_threshold: 0.0
  success_threshold: 0.2

  num_object_keypoints: 16
  gripper_keypoint_dof: 5
  gripper_keypoint_scale: 0.5

  partial_open_for_door: True
  partial_open_degree: 30

randomize:
  franka_arm_initial_dof_pos: [0, -0.5, 0, -3.0, 0, 3, 0.7854]
  franka_gripper_initial_state: 0.0

  object_pos_radius: 0.7
  object_pos_radius_noise: 0.05
  door_pos_radius_offset: 0.15
  object_pos_angle_noise: 1.57079   # pi / 2
  object_z_max: 0.80
  handle_z_min: 0.15
  door_rotation_noise: 0.26180      # pi / 12
  drawer_rotation_noise: 0.78540    # pi / 4

  object_dof_damping_lower: 1.0
  object_dof_damping_upper: 2.0
  object_dof_friction_lower: 0.25
  object_dof_friction_upper: 0.50
  door_damping_scale: 0.10
  door_friction_scale: 0.10

  max_object_init_dof_ratio: 0.6

ctrl:
  all:
    gripper_prop_gains: [200, 200]      # 500 -> 100 alleviate penetration
    gripper_deriv_gains: [1, 1]
  task_space_impedance:
    motion_ctrl_axes: [1, 1, 1, 1, 1, 1]
    task_prop_gains: [300, 300, 300, 50, 50, 50]
    task_deriv_gains: [34, 34, 34, 1.4, 1.4, 1.4]
