defaults:
    - IndustRealBase
    - _self_

name: 'place_cube'
use_init_states: True     
headless: True            # open viewer with render=True instead
physics_engine: "physx"

env:
  numEnvs: ${resolve_default:8192,${...num_envs}}
  numObservations: 30
  numActions: 6
  episode_length: 120

  val_ratio: ${resolve_default:0.0,${...val_ratio}}

  # camera properties
  camera:
    width: 1440
    height: 960

  object_friction: 1.0
  receptacle_friction: 1.0

  cube_size: 0.0385
  receptacle_size: 0.0496

sampler:
  # number of RL steps for pick policy
  num_rl_steps: 90
  # number of steps for closing gripper
  num_close_gripper_steps: 40
  # number of steps for lifting the arm
  num_lift_up_steps: 40
  # number of steps for randomizing franka and object pose
  num_randomization_steps: 30

  # for each pick result, we sample multiple randomized franka and object poses
  num_randomization_per_policy: 3
  # for each randomized franka and object pose, we sample multiple receptacle poses
  num_receptacle_pose_per_randomization: 5

  # configuration for pick cube policy
  policy_init_states_path: "init_states/franka_pick_cube_init_states.pt"
  policy_config_path: "config/train/pick_cube.yaml"
  policy_checkpoint_path: ${resolve_default:"checkpoints/pick_cube/franka_pick_cube.pth",${...checkpoint}}

  # noise for sampling receptacle position: 
  # for x and y axis, uniformly sample from [object_pos - receptacle_pos_noise, object_pos + receptacle_pos_noise]
  receptacle_pos_noise: 0.2

  # lower and upper bound for object height
  object_height_lower: 0.08
  object_height_upper: 0.16

rl:
  pos_action_scale: [0.05, 0.05, 0.05]
  rot_action_scale: [0.05, 0.05, 0.05]
  force_action_scale: [1.0, 1.0, 1.0]
  torque_action_scale: [1.0, 1.0, 1.0]

  clamp_rot: True
  clamp_rot_thresh: 1.0e-6

  max_episode_length: ${..env.episode_length}

  dist_object_reward_temp: -1.0
  dist_xy_reward_temp: -3.0
  
  object_keypoint_scale: 0.5
  success_xy_threshold: 0.015
  success_z_threshold: 0.005
  success_bonus: 0.0

  enable_object_in_view_reward: True
  object_in_view_reward_temp: -0.8
  object_in_view_reward_threshold: 0.30

randomize:
  franka_arm_initial_dof_pos: [0, 0.1963, 0, -2.0, 0, 2.3416, 0.7854]
  franka_gripper_initial_state: 0.0

ctrl:
  task_space_impedance:
    motion_ctrl_axes: [1, 1, 1, 1, 1, 1]
    task_prop_gains: [300, 300, 300, 50, 50, 50]
    task_deriv_gains: [34, 34, 34, 1.4, 1.4, 1.4]
