defaults:
  - base
  - _self_

task_instance_config:
  motion:
    duration: 8.0

  control:
    prop_gains: [1500, 1500, 1000, 50, 50, 50]
    # NOTE: deriv_gains computed automatically as 2 * sqrt(prop_gains)
    mode:
      type: leaky_plai  # options: nominal, plai, leaky_plai
      nominal:
        action_scale: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      plai:
        action_scale: [0.001, 0.001, 0.001, 0.004, 0.004, 0.004]
      leaky_plai:
        action_scale: [0.003, 0.003, 0.003, 0.0005, 0.0005, 0.0005]
        pos_err_thresh: [0.02, 0.02, 0.003]
        rot_err_thresh: 0.005     # degrees
